name: github/workflows/build.yml

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Buscar código
        uses: actions/checkout@v4

      - name: Instalar dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev build-essential

      - name: Instalar Buildozer
        run: |
          pip3 install --upgrade buildozer cython

      - name: Compilar APK
        run: |
          buildozer android debug

      - name: Guardar APK gerado
        uses: actions/upload-artifact@v4
        with:
          name: cobra-pro-apk
          path: bin/*.apk
